/* a32_runtime.h - guest state and helpers used by C code generated by a32_to_c.h.
 *
 * The generated code treats every AArch32 instruction as a few C statements
 * operating on an A32Context. Memory and supervisor calls go through functions
 * the host provides (a suyu HLE backend, or the test harness).
 *
 * Build generated code with -ffp-contract=off (MSVC: /fp:precise) so that
 * VMLA/VMLS stay two rounded operations and do not fuse into an FMA.
 */
#ifndef A32_RUNTIME_H
#define A32_RUNTIME_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct A32Context {
    uint32_t r[16];          /* r15 holds the address of the next block to run */
    uint32_t n, z, c, v, q;  /* APSR flags, each 0 or 1 */
    uint32_t ge;             /* APSR.GE[3:0] */
    uint32_t thumb;          /* set when an interworking branch selects Thumb */
    uint32_t fpscr;          /* NZCV live in bits 31:28 */
    union {
        uint32_t s[64];      /* s0..s31 overlay d0..d15 */
        uint64_t d[32];
    } ext;
    uint32_t halted;         /* nonzero stops the dispatcher; A32_HALT_UNHANDLED asks for the JIT */
    uint32_t tpidruro;       /* TPIDRURO - the AArch32 name for tpidrro_el0 (kernel TLS pointer) */
    uint32_t tpidrurw;       /* TPIDRURW - the guest's own thread pointer */
    uint32_t pending_svc;    /* SVC number parked for the HLE kernel, A32_NO_SVC otherwise */
    const struct A32HostMem* host;
} A32Context;

#define A32_NO_SVC 0xFFFFFFFFu
#define A32_HALT_UNHANDLED 2

/* The emulator side (src/core/arm/recomp/arm_recomp32.cpp) mirrors this layout;
 * nothing links the two builds, so both pin the offsets. */
#if defined(__cplusplus)
static_assert(offsetof(A32Context, ext) == 96, "A32Context layout");
static_assert(offsetof(A32Context, pending_svc) == 364, "A32Context layout");
static_assert(offsetof(A32Context, host) == 368, "A32Context layout");
#else
_Static_assert(offsetof(A32Context, ext) == 96, "A32Context layout");
_Static_assert(offsetof(A32Context, pending_svc) == 364, "A32Context layout");
_Static_assert(offsetof(A32Context, host) == 368, "A32Context layout");
#endif

/* Everything the generated code needs from the emulator. Filled in by the
 * backend; the page-table fields let mapped memory be accessed directly (a
 * null entry means unmapped or GPU-tracked memory and goes through load/store
 * so the rasterizer sees the access). */
typedef struct A32HostMem {
    void* user;
    uint64_t (*load)(void* user, uint64_t va, uint32_t size);
    void (*store)(void* user, uint64_t va, uint32_t size, uint64_t value);
    uint64_t (*excl_load)(void* user, uint64_t va, uint32_t size);
    uint32_t (*excl_store)(void* user, uint64_t va, uint32_t size, uint64_t value); /* 0 = success */
    void (*clear_excl)(void* user);
    uint64_t (*read_counter)(void* user);
    const void* page_entries;
    uint64_t page_entry_stride;
    uint64_t page_bits;
    uint64_t pointer_mask;
    uint64_t address_space_max;
    /* Block chaining: a static branch to a block of the same module calls that block directly
     * (A32_CHAIN) while chain_budget lasts; the dispatcher refills it before each block it runs
     * (0 = never chain). Guest addresses the host must see on entry (patched or traced
     * functions) are marked in hook_bits, one bit per word from hook_lo over hook_span bytes;
     * a branch to one of them always returns to the dispatcher. */
    int32_t chain_budget;
    uint32_t hook_lo;
    uint32_t hook_span;
    uint32_t chain_reserved;
    const volatile uint8_t* hook_bits;
} A32HostMem;

#if defined(__cplusplus)
static_assert(offsetof(A32HostMem, page_entries) == 56 && offsetof(A32HostMem, chain_budget) == 96 &&
              sizeof(A32HostMem) == 120, "A32HostMem layout");
#else
_Static_assert(offsetof(A32HostMem, page_entries) == 56 && offsetof(A32HostMem, chain_budget) == 96 &&
               sizeof(A32HostMem) == 120, "A32HostMem layout");
#endif

/* Module-relative PC constants. A generated project defines A32_PC in terms of
 * its module's load base; standalone users (tests) get identity. */
#ifndef A32_PC
#define A32_PC(off) ((uint32_t)(off))
#endif

static inline int a32_hooked(const A32HostMem* h, uint32_t pc) {
    const uint32_t d = pc - h->hook_lo;
    return d < h->hook_span && ((h->hook_bits[d >> 5] >> ((d >> 2) & 7)) & 1);
}

/* End of a block with a static target `off` (module offset) whose block function is `fn`:
 * run it directly when allowed, else hand it to the dispatcher. r15 is set either way (the
 * host's profiler reads it). */
#define A32_CHAIN(c, off, fn)                                                                  \
    do {                                                                                       \
        A32HostMem* a32_h_ = (A32HostMem*)(c)->host;                                           \
        (c)->r[15] = A32_PC(off);                                                              \
        if (--a32_h_->chain_budget > 0 && !a32_hooked(a32_h_, (c)->r[15])) {                   \
            fn(c);                                                                             \
        }                                                                                      \
        return;                                                                                \
    } while (0)

/* ---- provided by the host -------------------------------------------- */
uint8_t  a32_read8 (A32Context* c, uint32_t addr);
uint16_t a32_read16(A32Context* c, uint32_t addr);
uint32_t a32_read32(A32Context* c, uint32_t addr);
void     a32_write8 (A32Context* c, uint32_t addr, uint8_t v);
void     a32_write16(A32Context* c, uint32_t addr, uint16_t v);
void     a32_write32(A32Context* c, uint32_t addr, uint32_t v);
void     a32_svc(A32Context* c, uint32_t imm);
/* CNTPCT/CNTVCT read through MRRC p15 c14 */
uint64_t a32_read_counter(A32Context* c);
/* Exclusive monitor. size is 1, 2, 4 or 8; a32_excl_write returns 0 on success. */
uint64_t a32_excl_read(A32Context* c, uint32_t addr, unsigned size);
uint32_t a32_excl_write(A32Context* c, uint32_t addr, unsigned size, uint64_t value);
void     a32_clrex(A32Context* c);
/* Called for an instruction the lifter could not translate. r15 is set to its
 * address, so the host can resume there on a JIT/interpreter. */
void     a32_unhandled(A32Context* c, uint32_t insn, uint32_t pc);

/* ---- integer helpers --------------------------------------------------- */
static inline uint32_t a32_ror(uint32_t x, uint32_t r) {
    r &= 31;
    return r ? (x >> r) | (x << (32 - r)) : x;
}

/* Shift_C from the ARM ARM. type: 0 LSL, 1 LSR, 2 ASR, 3 ROR, 4 RRX.
 * amt is the already-decoded amount (1..32 for immediate forms, Rs[7:0] for
 * register forms); amt == 0 leaves value and carry unchanged. */
static inline uint32_t a32_shift_c(uint32_t v, uint32_t type, uint32_t amt, uint32_t cin,
                                   uint32_t* cout) {
    if (type == 4) {
        *cout = v & 1;
        return (v >> 1) | (cin << 31);
    }
    if (amt == 0) {
        *cout = cin;
        return v;
    }
    switch (type) {
    case 0:
        if (amt < 32) { *cout = (v >> (32 - amt)) & 1; return v << amt; }
        *cout = (amt == 32) ? (v & 1) : 0;
        return 0;
    case 1:
        if (amt < 32) { *cout = (v >> (amt - 1)) & 1; return v >> amt; }
        *cout = (amt == 32) ? (v >> 31) : 0;
        return 0;
    case 2:
        if (amt < 32) { *cout = (v >> (amt - 1)) & 1; return (uint32_t)((int32_t)v >> amt); }
        *cout = v >> 31;
        return (uint32_t)((int32_t)v >> 31);
    default: {
        uint32_t m = amt & 31;
        uint32_t r = m ? ((v >> m) | (v << (32 - m))) : v;
        *cout = r >> 31;
        return r;
    }
    }
}
static inline uint32_t a32_shift(uint32_t v, uint32_t type, uint32_t amt, uint32_t cin) {
    uint32_t co;
    return a32_shift_c(v, type, amt, cin, &co);
}

/* AddWithCarry. S is a compile-time constant in generated code. */
static inline uint32_t a32_awc(A32Context* c, uint32_t x, uint32_t y, uint32_t cin, int S) {
    uint64_t u = (uint64_t)x + y + cin;
    int64_t s = (int64_t)(int32_t)x + (int32_t)y + (int64_t)cin;
    uint32_t r = (uint32_t)u;
    if (S) {
        c->n = r >> 31;
        c->z = (r == 0);
        c->c = (uint32_t)(u >> 32) & 1;
        c->v = ((int64_t)(int32_t)r != s);
    }
    return r;
}
static inline uint32_t a32_nz(A32Context* c, uint32_t r) {
    c->n = r >> 31;
    c->z = (r == 0);
    return r;
}
static inline void a32_nz64(A32Context* c, uint64_t r) {
    c->n = (uint32_t)(r >> 63);
    c->z = (r == 0);
}

/* BXWritePC / LoadWritePC / ALUWritePC (ARMv7, ARM state). */
static inline void a32_bx_write_pc(A32Context* c, uint32_t t) {
    if (t & 1) {
        c->thumb = 1;
        c->r[15] = t & ~1u;
    } else {
        /* t<1:0> == 10 is UNPREDICTABLE; keep bit 1 like QEMU does */
        c->r[15] = t;
    }
}

static inline uint32_t a32_get_apsr(A32Context* c) {
    return (c->n << 31) | (c->z << 30) | (c->c << 29) | (c->v << 28) | (c->q << 27) |
           (c->ge << 16) | 0x10u /* user mode */;
}
/* mask bit1 = write NZCVQ, bit0 = write GE */
static inline void a32_set_apsr(A32Context* c, uint32_t v, uint32_t mask) {
    if (mask & 2) {
        c->n = (v >> 31) & 1; c->z = (v >> 30) & 1; c->c = (v >> 29) & 1;
        c->v = (v >> 28) & 1; c->q = (v >> 27) & 1;
    }
    if (mask & 1) c->ge = (v >> 16) & 0xF;
}

static inline uint32_t a32_clz(uint32_t x) {
#if defined(__GNUC__) || defined(__clang__)
    return x ? (uint32_t)__builtin_clz(x) : 32;
#else
    uint32_t n = 0;
    if (!x) return 32;
    while (!(x & 0x80000000u)) { x <<= 1; n++; }
    return n;
#endif
}
static inline uint32_t a32_rev(uint32_t x) {
    return (x >> 24) | ((x >> 8) & 0xFF00u) | ((x << 8) & 0xFF0000u) | (x << 24);
}
static inline uint32_t a32_rev16(uint32_t x) {
    return ((x >> 8) & 0x00FF00FFu) | ((x << 8) & 0xFF00FF00u);
}
static inline uint32_t a32_revsh(uint32_t x) {
    return (uint32_t)(int32_t)(int16_t)(uint16_t)(((x >> 8) & 0xFF) | ((x & 0xFF) << 8));
}
static inline uint32_t a32_rbit(uint32_t x) {
    uint32_t r = 0;
    for (int i = 0; i < 32; i++) { r = (r << 1) | (x & 1); x >>= 1; }
    return r;
}

/* Signed/unsigned saturation to n bits (SSAT n = 1..32, USAT n = 0..31). */
static inline uint32_t a32_ssat(A32Context* c, int64_t v, unsigned n) {
    int64_t hi = ((int64_t)1 << (n - 1)) - 1, lo = -((int64_t)1 << (n - 1));
    if (v > hi) { c->q = 1; return (uint32_t)hi; }
    if (v < lo) { c->q = 1; return (uint32_t)lo; }
    return (uint32_t)v;
}
static inline uint32_t a32_usat(A32Context* c, int64_t v, unsigned n) {
    int64_t hi = ((int64_t)1 << n) - 1;
    if (v > hi) { c->q = 1; return (uint32_t)hi; }
    if (v < 0) { c->q = 1; return 0; }
    return (uint32_t)v;
}
static inline uint32_t a32_sdiv(uint32_t n, uint32_t m) {
    if (m == 0) return 0;
    if (n == 0x80000000u && m == 0xFFFFFFFFu) return 0x80000000u;
    return (uint32_t)((int32_t)n / (int32_t)m);
}
static inline uint32_t a32_udiv(uint32_t n, uint32_t m) { return m ? n / m : 0; }

/* ---- VFP helpers --------------------------------------------------------- */
static inline float a32_gs(A32Context* c, unsigned i) { float f; memcpy(&f, &c->ext.s[i], 4); return f; }
static inline void a32_ss(A32Context* c, unsigned i, float f) { memcpy(&c->ext.s[i], &f, 4); }
static inline double a32_gd(A32Context* c, unsigned i) { double f; memcpy(&f, &c->ext.d[i], 8); return f; }
static inline void a32_sd(A32Context* c, unsigned i, double f) { memcpy(&c->ext.d[i], &f, 8); }

static inline void a32_fcmp(A32Context* c, double a, double b) {
    uint32_t f;
    if (a != a || b != b) f = 0x3;
    else if (a == b) f = 0x6;
    else if (a < b) f = 0x8;
    else f = 0x2;
    c->fpscr = (c->fpscr & 0x0FFFFFFFu) | (f << 28);
}
static inline void a32_vmrs_nzcv(A32Context* c) {
    c->n = c->fpscr >> 31; c->z = (c->fpscr >> 30) & 1;
    c->c = (c->fpscr >> 29) & 1; c->v = (c->fpscr >> 28) & 1;
}
/* FPToFixed(..., 0 fraction bits) with ARM's saturating semantics. rz: round toward zero. */
static inline uint32_t a32_f2s(double x, int rz) {
    if (x != x) return 0;
    double r = rz ? trunc(x) : nearbyint(x);
    if (r >= 2147483648.0) return 0x7FFFFFFFu;
    if (r < -2147483648.0) return 0x80000000u;
    return (uint32_t)(int32_t)r;
}
static inline uint32_t a32_f2u(double x, int rz) {
    if (x != x) return 0;
    double r = rz ? trunc(x) : nearbyint(x);
    if (r >= 4294967296.0) return 0xFFFFFFFFu;
    if (r < 0.0) return 0;
    return (uint32_t)r;
}
static inline uint64_t a32_read64(A32Context* c, uint32_t a) {
    uint64_t lo = a32_read32(c, a), hi = a32_read32(c, a + 4);
    return lo | (hi << 32);
}
static inline void a32_write64(A32Context* c, uint32_t a, uint64_t v) {
    a32_write32(c, a, (uint32_t)v);
    a32_write32(c, a + 4, (uint32_t)(v >> 32));
}


/* ---- ARM NaN semantics ------------------------------------------------
 * x86 and ARM disagree about NaN results: x86 creates 0xFFC00000 for an
 * invalid operation and returns the first *source* NaN; ARM creates the
 * default NaN 0x7FC00000 and picks signalling NaNs before quiet ones
 * (FPProcessNaNs). These wrappers compute on the host, then fix the result up
 * whenever it is a NaN, so every VFP result matches the guest bit for bit. */
static inline uint32_t a32_fbits(float f) { uint32_t b; memcpy(&b, &f, 4); return b; }
static inline float a32_ffrom(uint32_t b) { float f; memcpy(&f, &b, 4); return f; }
static inline uint64_t a32_dbits(double f) { uint64_t b; memcpy(&b, &f, 8); return b; }
static inline double a32_dfrom(uint64_t b) { double f; memcpy(&f, &b, 8); return f; }
static inline int a32_snan_s(float f) { uint32_t b = a32_fbits(f); return (b & 0x7FC00000u) == 0x7F800000u && (b & 0x003FFFFFu); }
static inline int a32_snan_d(double f) { uint64_t b = a32_dbits(f); return (b & 0x7FF8000000000000ull) == 0x7FF0000000000000ull && (b & 0x0007FFFFFFFFFFFFull); }
static inline float a32_quiet_s(float f) { return a32_ffrom(a32_fbits(f) | 0x00400000u); }
static inline double a32_quiet_d(double f) { return a32_dfrom(a32_dbits(f) | 0x0008000000000000ull); }
#define A32_DNAN_S a32_ffrom(0x7FC00000u)
#define A32_DNAN_D a32_dfrom(0x7FF8000000000000ull)

static inline float a32_nan1_s(float r, float a) {
    if (r == r) return r;
    return (a != a) ? a32_quiet_s(a) : A32_DNAN_S;
}
static inline double a32_nan1_d(double r, double a) {
    if (r == r) return r;
    return (a != a) ? a32_quiet_d(a) : A32_DNAN_D;
}
static inline float a32_nan2_s(float r, float a, float b) {
    if (r == r) return r;
    if (a32_snan_s(a)) return a32_quiet_s(a);
    if (a32_snan_s(b)) return a32_quiet_s(b);
    if (a != a) return a;
    if (b != b) return b;
    return A32_DNAN_S;
}
static inline double a32_nan2_d(double r, double a, double b) {
    if (r == r) return r;
    if (a32_snan_d(a)) return a32_quiet_d(a);
    if (a32_snan_d(b)) return a32_quiet_d(b);
    if (a != a) return a;
    if (b != b) return b;
    return A32_DNAN_D;
}
static inline float a32_nan3_s(float r, float a, float b, float c) {
    if (r == r) return r;
    if (a32_snan_s(a)) return a32_quiet_s(a);
    if (a32_snan_s(b)) return a32_quiet_s(b);
    if (a32_snan_s(c)) return a32_quiet_s(c);
    if (a != a) return a;
    if (b != b) return b;
    if (c != c) return c;
    return A32_DNAN_S;
}
static inline double a32_nan3_d(double r, double a, double b, double c) {
    if (r == r) return r;
    if (a32_snan_d(a)) return a32_quiet_d(a);
    if (a32_snan_d(b)) return a32_quiet_d(b);
    if (a32_snan_d(c)) return a32_quiet_d(c);
    if (a != a) return a;
    if (b != b) return b;
    if (c != c) return c;
    return A32_DNAN_D;
}
static inline float a32_add_s(float a, float b) { return a32_nan2_s(a + b, a, b); }
static inline float a32_sub_s(float a, float b) { return a32_nan2_s(a - b, a, b); }
static inline float a32_mul_s(float a, float b) { return a32_nan2_s(a * b, a, b); }
static inline float a32_div_s(float a, float b) { return a32_nan2_s(a / b, a, b); }
static inline double a32_add_d(double a, double b) { return a32_nan2_d(a + b, a, b); }
static inline double a32_sub_d(double a, double b) { return a32_nan2_d(a - b, a, b); }
static inline double a32_mul_d(double a, double b) { return a32_nan2_d(a * b, a, b); }
static inline double a32_div_d(double a, double b) { return a32_nan2_d(a / b, a, b); }
/* FPMulAdd(addend, n, m): NaN operand order is addend, n, m. One special case:
 * an inf*0 product with a quiet-NaN addend gives the default NaN on ARM. */
static inline float a32_fma_s(float d, float n, float m) {
    float r = fmaf(n, m, d);
    if (r == r) return r;
    if (!a32_snan_s(d) && d != d && ((isinf(n) && m == 0) || (n == 0 && isinf(m))) && n == n && m == m) return A32_DNAN_S;
    return a32_nan3_s(r, d, n, m);
}
static inline double a32_fma_d(double d, double n, double m) {
    double r = fma(n, m, d);
    if (r == r) return r;
    if (!a32_snan_d(d) && d != d && ((isinf(n) && m == 0) || (n == 0 && isinf(m))) && n == n && m == m) return A32_DNAN_D;
    return a32_nan3_d(r, d, n, m);
}

/* ARMv8 FP helpers ---------------------------------------------------- */
/* IEEE maxNum/minNum as used by VMAXNM/VMINNM: a quiet NaN loses to a number;
 * +0 is larger than -0. */
static inline double a32_maxnm(double a, double b) {
    if (a32_snan_d(a)) return a32_quiet_d(a);
    if (a32_snan_d(b)) return a32_quiet_d(b);
    if (a != a) return (b != b) ? a : b;
    if (b != b) return a;
    if (a == 0 && b == 0) return signbit(a) ? b : a;
    return a > b ? a : b;
}
static inline double a32_minnm(double a, double b) {
    if (a32_snan_d(a)) return a32_quiet_d(a);
    if (a32_snan_d(b)) return a32_quiet_d(b);
    if (a != a) return (b != b) ? a : b;
    if (b != b) return a;
    if (a == 0 && b == 0) return signbit(a) ? a : b;
    return a < b ? a : b;
}
/* single-precision versions: promoting a signalling NaN to double would quiet it */
static inline float a32_maxnm_s(float a, float b) {
    if (a32_snan_s(a)) return a32_quiet_s(a);
    if (a32_snan_s(b)) return a32_quiet_s(b);
    if (a != a) return (b != b) ? a : b;
    if (b != b) return a;
    if (a == 0 && b == 0) return signbit(a) ? b : a;
    return a > b ? a : b;
}
static inline float a32_minnm_s(float a, float b) {
    if (a32_snan_s(a)) return a32_quiet_s(a);
    if (a32_snan_s(b)) return a32_quiet_s(b);
    if (a != a) return (b != b) ? a : b;
    if (b != b) return a;
    if (a == 0 && b == 0) return signbit(a) ? a : b;
    return a < b ? a : b;
}
/* VRINT on a float NaN: quiet the input itself, keeping its payload exactly */
static inline float a32_quiet_nan_s(float in, float r) { return (in != in) ? a32_quiet_s(in) : r; }
/* rounding modes used by VRINT{A,N,P,M} / VCVT{A,N,P,M}: 0 A, 1 N, 2 P, 3 M */
static inline double a32_round(double x, int mode) {
    switch (mode) {
    case 0: return round(x);
    case 1: return nearbyint(x); /* host runs round-to-nearest-even */
    case 2: return ceil(x);
    default: return floor(x);
    }
}
/* Advanced SIMD float ops run with the "standard FPSCR": flush-to-zero and default NaN. */
static inline float a32_ftz(float x) {
    uint32_t b; memcpy(&b, &x, 4);
    if ((b & 0x7F800000u) == 0 && (b & 0x007FFFFFu)) { b &= 0x80000000u; memcpy(&x, &b, 4); }
    return x;
}
static inline uint32_t a32_neon_fmaxmin(uint32_t ab, uint32_t bb, int is_min) {
    float a, b; memcpy(&a, &ab, 4); memcpy(&b, &bb, 4);
    a = a32_ftz(a); b = a32_ftz(b);
    if (a != a || b != b) return 0x7FC00000u;
    float r;
    if (a == 0 && b == 0) r = (signbit(a) != signbit(b)) ? (is_min ? -0.0f : 0.0f) : a;
    else r = is_min ? (a < b ? a : b) : (a > b ? a : b);
    uint32_t rb; memcpy(&rb, &r, 4);
    return rb;
}
static inline uint32_t a32_crc32(uint32_t acc, uint32_t val, int bytes, int castagnoli) {
    const uint32_t poly = castagnoli ? 0x82F63B78u : 0xEDB88320u;
    for (int k = 0; k < bytes; k++) {
        acc ^= (val >> (8 * k)) & 0xFF;
        for (int b = 0; b < 8; b++) acc = (acc >> 1) ^ (poly & (0u - (acc & 1)));
    }
    return acc;
}

/* Advanced SIMD float arithmetic: standard FPSCR (inputs and results flushed, default NaN). */
static inline float a32_nf_in(uint32_t b) { float f; memcpy(&f, &b, 4); return a32_ftz(f); }
static inline uint32_t a32_nf_out(float r) {
    r = a32_ftz(r);
    if (r != r) return 0x7FC00000u;
    uint32_t b; memcpy(&b, &r, 4);
    return b;
}
static inline uint32_t a32_nfadd(uint32_t a, uint32_t b) { return a32_nf_out(a32_nf_in(a) + a32_nf_in(b)); }
static inline uint32_t a32_nfsub(uint32_t a, uint32_t b) { return a32_nf_out(a32_nf_in(a) - a32_nf_in(b)); }
static inline uint32_t a32_nfmul(uint32_t a, uint32_t b) { return a32_nf_out(a32_nf_in(a) * a32_nf_in(b)); }
static inline uint32_t a32_nfabd(uint32_t a, uint32_t b) { return a32_nf_out(fabsf(a32_nf_in(a) - a32_nf_in(b))); }
/* VMLA / VMLS: product rounded first, then the add (not fused) */
static inline uint32_t a32_nfmla(uint32_t d, uint32_t a, uint32_t b, int sub) {
    const uint32_t p = a32_nfmul(a, b);
    return sub ? a32_nfsub(d, p) : a32_nfadd(d, p);
}
/* compares: 0 eq, 1 ge, 2 gt, 3 abs ge, 4 abs gt; all ones when true */
static inline uint32_t a32_nfcmp(uint32_t ab, uint32_t bb, int op) {
    float a = a32_nf_in(ab), b = a32_nf_in(bb);
    if (op >= 3) { a = fabsf(a); b = fabsf(b); }
    const int r = op == 0 ? a == b : (op == 1 || op == 3) ? a >= b : a > b;
    return r ? 0xFFFFFFFFu : 0;
}
/* VRECPS: 2 - a*b, VRSQRTS: (3 - a*b) / 2, the product rounded first; infinity times zero
 * gives 2 / 1.5 */
static inline uint32_t a32_nfstep(uint32_t ab, uint32_t bb, int rsqrt) {
    const float a = a32_nf_in(ab), b = a32_nf_in(bb);
    if ((isinf(a) && b == 0) || (a == 0 && isinf(b))) return rsqrt ? 0x3FC00000u : 0x40000000u;
    if (a != a || b != b) return 0x7FC00000u;
    const float p = a32_nf_in(a32_nfmul(ab, bb));
    return a32_nf_out(rsqrt ? (3.0f - p) * 0.5f : 2.0f - p);
}

/* VRECPE.F32 / VRSQRTE.F32: the architecture's 8-bit estimates (standard FPSCR) */
static inline uint32_t a32_nfrecpe(uint32_t x) {
    const uint32_t sign = x & 0x80000000u, exp = (x >> 23) & 0xFF;
    if (exp == 0xFF) return (x & 0x007FFFFFu) ? 0x7FC00000u : sign; /* NaN / +-inf -> +-0 */
    if (exp == 0) return sign | 0x7F800000u;                           /* zero, flushed denormal -> inf */
    if (exp >= 253) return sign;                                       /* result would be denormal: flushed */
    uint32_t a = 256 + ((x >> 15) & 0xFF);                             /* 0.5 <= a/512 < 1 */
    a = a * 2 + 1;
    const uint32_t b = (1u << 19) / a, r = (b + 1) / 2;                /* 256..511 */
    return sign | ((253 - exp) << 23) | ((r & 0xFF) << 15);
}
static inline uint32_t a32_nfrsqrte(uint32_t x) {
    const uint32_t sign = x & 0x80000000u, exp = (x >> 23) & 0xFF;
    if (exp == 0xFF && (x & 0x007FFFFFu)) return 0x7FC00000u;
    if (exp == 0) return sign | 0x7F800000u;
    if (sign) return 0x7FC00000u;
    if (exp == 0xFF) return 0;
    uint32_t a = (exp & 1) ? 128 + ((x >> 16) & 0x7F) : 256 + ((x >> 15) & 0xFF);
    if (a < 256) a = a * 2 + 1;
    else { a = (a >> 1) << 1; a = (a + 1) * 2; }
    uint32_t b = 512;
    while ((uint64_t)a * (b + 1) * (b + 1) < (1ull << 28)) b++;
    const uint32_t r = (b + 1) / 2;
    return ((((380 - exp) / 2) & 0xFF) << 23) | ((r & 0xFF) << 15);
}

/* Crypto extension. Q registers are passed as their four 32-bit words (w[0] lowest). */
static const uint8_t a32_aes_sbox[256] = {
    0x63,0x7c,0x77,0x7b,0xf2,0x6b,0x6f,0xc5,0x30,0x01,0x67,0x2b,0xfe,0xd7,0xab,0x76,0xca,0x82,0xc9,0x7d,0xfa,0x59,0x47,0xf0,
    0xad,0xd4,0xa2,0xaf,0x9c,0xa4,0x72,0xc0,0xb7,0xfd,0x93,0x26,0x36,0x3f,0xf7,0xcc,0x34,0xa5,0xe5,0xf1,0x71,0xd8,0x31,0x15,
    0x04,0xc7,0x23,0xc3,0x18,0x96,0x05,0x9a,0x07,0x12,0x80,0xe2,0xeb,0x27,0xb2,0x75,0x09,0x83,0x2c,0x1a,0x1b,0x6e,0x5a,0xa0,
    0x52,0x3b,0xd6,0xb3,0x29,0xe3,0x2f,0x84,0x53,0xd1,0x00,0xed,0x20,0xfc,0xb1,0x5b,0x6a,0xcb,0xbe,0x39,0x4a,0x4c,0x58,0xcf,
    0xd0,0xef,0xaa,0xfb,0x43,0x4d,0x33,0x85,0x45,0xf9,0x02,0x7f,0x50,0x3c,0x9f,0xa8,0x51,0xa3,0x40,0x8f,0x92,0x9d,0x38,0xf5,
    0xbc,0xb6,0xda,0x21,0x10,0xff,0xf3,0xd2,0xcd,0x0c,0x13,0xec,0x5f,0x97,0x44,0x17,0xc4,0xa7,0x7e,0x3d,0x64,0x5d,0x19,0x73,
    0x60,0x81,0x4f,0xdc,0x22,0x2a,0x90,0x88,0x46,0xee,0xb8,0x14,0xde,0x5e,0x0b,0xdb,0xe0,0x32,0x3a,0x0a,0x49,0x06,0x24,0x5c,
    0xc2,0xd3,0xac,0x62,0x91,0x95,0xe4,0x79,0xe7,0xc8,0x37,0x6d,0x8d,0xd5,0x4e,0xa9,0x6c,0x56,0xf4,0xea,0x65,0x7a,0xae,0x08,
    0xba,0x78,0x25,0x2e,0x1c,0xa6,0xb4,0xc6,0xe8,0xdd,0x74,0x1f,0x4b,0xbd,0x8b,0x8a,0x70,0x3e,0xb5,0x66,0x48,0x03,0xf6,0x0e,
    0x61,0x35,0x57,0xb9,0x86,0xc1,0x1d,0x9e,0xe1,0xf8,0x98,0x11,0x69,0xd9,0x8e,0x94,0x9b,0x1e,0x87,0xe9,0xce,0x55,0x28,0xdf,
    0x8c,0xa1,0x89,0x0d,0xbf,0xe6,0x42,0x68,0x41,0x99,0x2d,0x0f,0xb0,0x54,0xbb,0x16};
static inline uint8_t a32_gmul(uint8_t a, uint8_t b) {
    uint8_t r = 0;
    while (b) {
        if (b & 1) r ^= a;
        a = (uint8_t)((a << 1) ^ ((a & 0x80) ? 0x1B : 0));
        b >>= 1;
    }
    return r;
}
/* op: 0 AESE, 1 AESD, 2 AESMC, 3 AESIMC; d and m index D registers (Qd = d, d+1) */
static inline void a32_aes(A32Context* c, unsigned d, unsigned m, int op) {
    uint8_t in[16], out[16];
    memcpy(in, &c->ext.d[m], 16);
    if (op < 2) {
        uint8_t st[16];
        memcpy(st, &c->ext.d[d], 16);
        for (int k = 0; k < 16; k++) st[k] ^= in[k];
        uint8_t inv[256];
        if (op == 1) for (int k = 0; k < 256; k++) inv[a32_aes_sbox[k]] = (uint8_t)k;
        for (int col = 0; col < 4; col++)
            for (int row = 0; row < 4; row++) {
                const int src = op == 0 ? (col + row) & 3 : (col - row) & 3;
                const uint8_t v = st[row + 4 * src];
                out[row + 4 * col] = op == 0 ? a32_aes_sbox[v] : inv[v];
            }
    } else {
        static const uint8_t mc[4] = {2, 3, 1, 1}, imc[4] = {14, 11, 13, 9};
        const uint8_t* coef = op == 2 ? mc : imc;
        for (int col = 0; col < 4; col++)
            for (int row = 0; row < 4; row++) {
                uint8_t v = 0;
                for (int k = 0; k < 4; k++) v ^= a32_gmul(in[4 * col + k], coef[(k - row) & 3]);
                out[4 * col + row] = v;
            }
    }
    memcpy(&c->ext.d[d], out, 16);
}
static inline uint32_t a32_rol(uint32_t x, int n) { return (x << n) | (x >> ((32 - n) & 31)); }
/* three-register SHA. op: 0 SHA1C, 1 SHA1P, 2 SHA1M, 3 SHA1SU0, 4 SHA256H, 5 SHA256H2, 6 SHA256SU1 */
static inline void a32_sha3(A32Context* c, unsigned d, unsigned n, unsigned m, int op) {
    uint32_t X[4], Y[4], W[4], R[4];
    memcpy(X, &c->ext.d[d], 16); memcpy(Y, &c->ext.d[n], 16); memcpy(W, &c->ext.d[m], 16);
    if (op <= 2) {
        uint32_t y = Y[0];
        for (int e = 0; e < 4; e++) {
            const uint32_t a = X[1], b = X[2], cc = X[3];
            const uint32_t t = op == 0 ? (((b ^ cc) & a) ^ cc) : op == 1 ? (a ^ b ^ cc) : ((a & b) | ((a | b) & cc));
            y = y + a32_rol(X[0], 5) + t + W[e];
            X[1] = a32_rol(X[1], 30);
            const uint32_t top = X[3];
            X[3] = X[2]; X[2] = X[1]; X[1] = X[0]; X[0] = y; y = top;
        }
        memcpy(R, X, 16);
    } else if (op == 3) {
        R[0] = X[2] ^ X[0] ^ W[0]; R[1] = X[3] ^ X[1] ^ W[1]; R[2] = Y[0] ^ X[2] ^ W[2]; R[3] = Y[1] ^ X[3] ^ W[3];
    } else if (op <= 5) {
        uint32_t x[4], y[4];
        if (op == 4) { memcpy(x, X, 16); memcpy(y, Y, 16); } else { memcpy(x, Y, 16); memcpy(y, X, 16); }
        for (int e = 0; e < 4; e++) {
            const uint32_t chs = ((y[1] ^ y[2]) & y[0]) ^ y[2];
            const uint32_t maj = (x[0] & x[1]) | ((x[0] | x[1]) & x[2]);
            const uint32_t s1 = a32_ror(y[0], 6) ^ a32_ror(y[0], 11) ^ a32_ror(y[0], 25);
            const uint32_t s0 = a32_ror(x[0], 2) ^ a32_ror(x[0], 13) ^ a32_ror(x[0], 22);
            const uint32_t t = y[3] + s1 + chs + W[e];
            x[3] = t + x[3];
            y[3] = t + s0 + maj;
            const uint32_t xt = x[3], yt = y[3];
            x[3] = x[2]; x[2] = x[1]; x[1] = x[0]; x[0] = yt;
            y[3] = y[2]; y[2] = y[1]; y[1] = y[0]; y[0] = xt;
        }
        memcpy(R, op == 4 ? x : y, 16);
    } else {
        const uint32_t T0[4] = {Y[1], Y[2], Y[3], W[0]};
        for (int e = 0; e < 2; e++) {
            const uint32_t v = W[2 + e];
            R[e] = (a32_ror(v, 17) ^ a32_ror(v, 19) ^ (v >> 10)) + X[e] + T0[e];
        }
        for (int e = 2; e < 4; e++) {
            const uint32_t v = R[e - 2];
            R[e] = (a32_ror(v, 17) ^ a32_ror(v, 19) ^ (v >> 10)) + X[e] + T0[e];
        }
    }
    memcpy(&c->ext.d[d], R, 16);
}
/* two-register SHA. op: 0 SHA1H, 1 SHA1SU1, 2 SHA256SU0 */
static inline void a32_sha2(A32Context* c, unsigned d, unsigned m, int op) {
    uint32_t X[4], Y[4], R[4];
    memcpy(X, &c->ext.d[d], 16); memcpy(Y, &c->ext.d[m], 16);
    if (op == 0) {
        R[0] = a32_rol(Y[0], 30); R[1] = R[2] = R[3] = 0;
    } else if (op == 1) {
        const uint32_t T[4] = {X[0] ^ Y[1], X[1] ^ Y[2], X[2] ^ Y[3], X[3]};
        R[0] = a32_rol(T[0], 1); R[1] = a32_rol(T[1], 1); R[2] = a32_rol(T[2], 1);
        R[3] = a32_rol(T[3], 1) ^ a32_rol(T[0], 2);
    } else {
        const uint32_t T[4] = {X[1], X[2], X[3], Y[0]};
        for (int e = 0; e < 4; e++) R[e] = (a32_ror(T[e], 7) ^ a32_ror(T[e], 18) ^ (T[e] >> 3)) + X[e];
    }
    memcpy(&c->ext.d[d], R, 16);
}

typedef void (*A32BlockFn)(A32Context*);

#ifdef __cplusplus
}
#endif
#endif /* A32_RUNTIME_H */
