#!/usr/bin/env python3
"""Embed a32_runtime.h and a32_host_runtime.c as C++ string constants.

MSVC caps one string literal at ~16 KB, so the text is split into several
adjacent raw literals."""
import sys, os
here = os.path.dirname(os.path.abspath(__file__))
out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "a32_runtime_sources.h")
DELIM = "A32RT"
def literal(text):
    assert f'){DELIM}"' not in text
    parts, chunk = [], 8000
    for i in range(0, len(text), chunk):
        parts.append(f'R"{DELIM}({text[i:i + chunk]}){DELIM}"')
    return "\n    ".join(parts)
with open(out, "w", newline="\n") as f:
    f.write("// auto-generated by embed_runtime.py from a32_runtime.h / a32_host_runtime.c - DO NOT EDIT\n")
    f.write("#pragma once\n#include <string>\n\nnamespace a32recomp {\n\n")
    for name, fn in (("kRuntimeH", "a32_runtime.h"), ("kHostRuntimeC", "a32_host_runtime.c")):
        text = open(os.path.join(here, fn)).read()
        f.write(f"inline const std::string {name} =\n    {literal(text)};\n\n")
    f.write("} // namespace a32recomp\n")
print("wrote", out)
