// a32emit.h - write a buildable C project for one recompiled AArch32 module.
//
// Same outward shape as suyu's AArch64 EmitProject (core/recompiler/arm64_to_c.h),
// so the rest of suyu's export pipeline treats the two alike:
//   <out>/CMakeLists.txt          static library recomp_static_<mod>
//   <out>/recomp_export.c         recomp_image_lookup / recomp_image_set_base / recomp_image_entry
//   <out>/module.h                A32_PC() in terms of this module's load base
//   <out>/a32_runtime.h           shared runtime header (copied)
//   <out>/a32_host_runtime.c      hosted runtime (built once as a32_runtime_shared)
//   <out>/src/blocks_<n>.c        block functions b_<mod>_<offset>
//   <out>/src/dispatch.c          sorted offset table + binary-search lookup
//
// As in the AArch64 path the static library is linked several times into one
// executable, so module-owned symbols are renamed per module at compile time
// (-Dg_module_base=g_module_base_<mod> ...) and block names carry the module.
#pragma once

#include "a32disc.h"
#include <filesystem>
#include <fstream>
#include <sstream>
#include <unordered_set>

namespace a32recomp {

struct EmitStats {
    size_t blocks = 0, instructions = 0, unhandled = 0, files = 0;
    size_t code_words = 0, data_words = 0, unknown_words = 0, text_words = 0;
    size_t chained = 0; // static branch exits that call their target block directly
};

// UTF-8 path helper: game names routinely carry non-ASCII characters.
inline std::filesystem::path A32Path(const std::string& s) {
#if defined(__cpp_char8_t)
    return std::filesystem::path(std::u8string(reinterpret_cast<const char8_t*>(s.data()), s.size()));
#else
    return std::filesystem::u8path(s);
#endif
}

// The runtime sources are embedded so the emitter needs no files beside it.
// They are passed in by the caller (the suyu exporter reads them from its
// resources; a32cov reads them from disk).
struct RuntimeSources {
    std::string runtime_h;
    std::string host_runtime_c;
};

inline EmitStats EmitProject32(const std::string& mod, const NsoImage& img, const Discovery& d,
                               const std::string& out_dir, const RuntimeSources& rt,
                               unsigned nfiles = 64) {
    namespace fs = std::filesystem;
    EmitStats st;
    fs::create_directories(A32Path(out_dir + "/src"));
    auto write = [&](const std::string& rel, const std::string& data) {
        std::ofstream o(A32Path(out_dir + "/" + rel), std::ios::binary);
        o.write(data.data(), (std::streamsize)data.size());
    };

    for (u8 k : d.kind) {
        if (k == Discovery::Code) st.code_words++;
        else if (k == Discovery::Data) st.data_words++;
        else st.unknown_words++;
    }
    st.text_words = d.kind.size();

    std::vector<u32> starts(d.block_starts.begin(), d.block_starts.end());
    st.blocks = starts.size();
    if (starts.empty()) return st;
    nfiles = std::max(1u, std::min<unsigned>(nfiles, (unsigned)starts.size()));
    st.files = nfiles;

    // ---- block functions
    const std::string header = "/* auto-generated by a32recomp - DO NOT EDIT */\n#include \"module.h\"\n\n";
    std::vector<std::ofstream> outs(nfiles);
    for (unsigned k = 0; k < nfiles; ++k) {
        outs[k].open(A32Path(out_dir + "/src/blocks_" + std::to_string(k) + ".c"), std::ios::binary);
        outs[k] << header;
    }
    auto name = [&](u32 off) { return F("b_%s_%08X", mod.c_str(), off); };
    // Block chaining: a block exit to a fixed target that is itself a block of this module
    // calls it directly (A32_CHAIN; the host still sees hooked targets and bounds the chain).
    // Not after an interworking branch (Thumb target) or an SVC / unhandled exit, which
    // don't use this exact form.
    const std::unordered_set<u32> start_set(starts.begin(), starts.end());
    auto chain = [&](const std::string& body, std::string& decls) {
        static const std::string kHead = "c->r[15] = A32_PC(0x";
        static const std::string kTail = "u); return;";
        static const std::string kThumb = "c->thumb = 1; ";
        std::string out;
        out.reserve(body.size() + 64);
        size_t last = 0;
        for (size_t at = body.find(kHead); at != std::string::npos; at = body.find(kHead, at + 1)) {
            const size_t hex = at + kHead.size();
            if (hex + 8 + kTail.size() > body.size() ||
                body.compare(hex + 8, kTail.size(), kTail) != 0) {
                continue;
            }
            const bool after_thumb =
                at >= kThumb.size() && body.compare(at - kThumb.size(), kThumb.size(), kThumb) == 0;
            const u32 tgt = (u32)std::stoul(body.substr(hex, 8), nullptr, 16);
            if (after_thumb || start_set.count(tgt) == 0) {
                continue;
            }
            out.append(body, last, at - last);
            out += F("A32_CHAIN(c, 0x%08Xu, %s);", tgt, name(tgt).c_str());
            last = hex + 8 + kTail.size();
            decls += "void " + name(tgt) + "(A32Context*);\n";
            st.chained++;
        }
        out.append(body, last, std::string::npos);
        return out;
    };
    for (size_t b = 0; b < starts.size(); ++b) {
        const u32 a = starts[b];
        const u32 limit = (b + 1 < starts.size()) ? starts[b + 1] : img.text_off + img.text_size;
        std::string body;
        u32 pc = a;
        bool open = true;
        while (open && pc < limit && d.kind[(pc - img.text_off) / 4] == Discovery::Code) {
            bool unh = false;
            open = Translate(img.Word(pc), pc, body, &unh);
            st.instructions++;
            st.unhandled += unh;
            pc += 4;
        }
        if (open) body += "    c->r[15] = " + PcConst(pc) + "; return;\n";
        std::string decls;
        body = chain(body, decls);
        outs[b * nfiles / starts.size()] << decls << "void " << name(a) << "(A32Context* c) {\n" << body << "}\n\n";
    }
    for (auto& o : outs) o.close();

    // ---- dispatch table: sorted module offsets and matching functions
    {
        std::ostringstream t;
        t << header;
        for (u32 a : starts) t << "void " << name(a) << "(A32Context*);\n";
        t << "\nstatic const uint32_t s_off[] = {\n";
        for (size_t b = 0; b < starts.size(); ++b) t << F("0x%Xu,", starts[b]) << ((b % 8 == 7) ? "\n" : "");
        t << "\n};\nstatic const A32BlockFn s_fn[] = {\n";
        for (u32 a : starts) t << "    " << name(a) << ",\n";
        t << "};\n\n"
             "A32BlockFn a32_module_lookup(uint32_t off) {\n"
             "    size_t lo = 0, hi = sizeof(s_off) / sizeof(s_off[0]);\n"
             "    while (lo < hi) {\n"
             "        size_t mid = (lo + hi) / 2;\n"
             "        if (s_off[mid] < off) lo = mid + 1; else hi = mid;\n"
             "    }\n"
             "    return (lo < sizeof(s_off) / sizeof(s_off[0]) && s_off[lo] == off) ? s_fn[lo] : 0;\n"
             "}\n";
        write("src/dispatch.c", t.str());
    }

    // ---- module.h / export
    write("module.h",
          "/* auto-generated by a32recomp - DO NOT EDIT */\n"
          "#ifndef A32_MODULE_H\n#define A32_MODULE_H\n"
          "#include <stdint.h>\n"
          "extern uint64_t g_module_base;\n"
          "/* Guest address of a module offset: the loader chooses the base at run time. */\n"
          "#define A32_PC(off) ((uint32_t)(g_module_base + (off)))\n"
          "#include \"a32_runtime.h\"\n"
          "A32BlockFn a32_module_lookup(uint32_t off);\n"
          "#endif\n");
    {
        std::ostringstream ex;
        ex << "/* auto-generated by a32recomp - DO NOT EDIT */\n"
              "#include \"module.h\"\n\n"
              "uint64_t g_module_base = 0;\n\n"
              "/* Same entry points as suyu's AArch64 images, so recomp_registration.c\n"
              "   and suyu-cmd need no 32-bit special case. */\n"
              "A32BlockFn recomp_image_lookup(uint64_t pc) {\n"
              "    const uint64_t off = pc - g_module_base;\n"
           << F("    if (!g_module_base || pc < g_module_base || off >= 0x%Xu) return 0; /* base unset: not loaded */\n", img.text_off + img.text_size)
           << "    return a32_module_lookup((uint32_t)off);\n"
              "}\n"
              "void recomp_image_set_base(uint64_t base) { g_module_base = base; }\n"
           << F("uint64_t recomp_image_entry(void) { return g_module_base + 0x%Xu; }\n", img.text_off)
           << "/* Lets the host tell a 32-bit image from a 64-bit one. */\n"
              "int recomp_image_is_a32(void) { return 1; }\n";
        write("recomp_export.c", ex.str());
    }
    write("a32_runtime.h", rt.runtime_h);
    write("a32_host_runtime.c", rt.host_runtime_c);

    // ---- CMake
    {
        std::ostringstream cm;
        cm << "# auto-generated by a32recomp - DO NOT EDIT\n"
              "cmake_minimum_required(VERSION 3.13)\n"
              "project(recomp_a32_" << mod << " C)\n"
              "set(CMAKE_C_STANDARD 11)\n"
              "# Inside suyu's tree this directory inherits suyu's C++-only MSVC options\n"
              "# (/std:c++20 clashes with /std:c11) and its warnings-as-errors; drop them\n"
              "# for this generated C.\n"
              "if(MSVC)\n"
              "  get_directory_property(_a32_opts COMPILE_OPTIONS)\n"
              "  list(FILTER _a32_opts EXCLUDE REGEX \"^/std:c\\\\+\\\\+|^/EHsc$|^/Zc:externConstexpr$|^/Zc:throwingNew$|^/we[0-9]+$|^/W[0-4]$|^/WX\")\n"
              "  set_directory_properties(PROPERTIES COMPILE_OPTIONS \"${_a32_opts}\")\n"
              "  add_compile_options(/W1)\n"
              "endif()\n"
              "file(GLOB RECOMP_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/*.c)\n"
              "if(NOT TARGET a32_runtime_shared)\n"
              "  add_library(a32_runtime_shared STATIC a32_host_runtime.c)\n"
              "  target_include_directories(a32_runtime_shared PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})\n"
              "endif()\n"
              "add_library(recomp_static_" << mod << " STATIC recomp_export.c ${RECOMP_SOURCES})\n"
              "target_include_directories(recomp_static_" << mod << " PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})\n"
              "target_link_libraries(recomp_static_" << mod << " PUBLIC a32_runtime_shared)\n"
              "target_compile_definitions(recomp_static_" << mod << " PRIVATE"
              " g_module_base=g_module_base_" << mod <<
              " a32_module_lookup=a32_module_lookup_" << mod <<
              " recomp_image_lookup=recomp_image_lookup_" << mod <<
              " recomp_image_set_base=recomp_image_set_base_" << mod <<
              " recomp_image_entry=recomp_image_entry_" << mod <<
              " recomp_image_is_a32=recomp_image_is_a32_" << mod << ")\n"
              "# VMLA/VMLS must stay two roundings: no FMA contraction.\n"
              "if(MSVC)\n"
              "  target_compile_options(recomp_static_" << mod << " PRIVATE /fp:precise /bigobj /O1)\n"
              "else()\n"
              "  target_compile_options(recomp_static_" << mod << " PRIVATE -ffp-contract=off -fno-strict-aliasing -O1)\n"
              "endif()\n";
        write("CMakeLists.txt", cm.str());
    }
    return st;
}

} // namespace a32recomp
